/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define PCR_IBE_ibe1 0x01u /*!<@brief Input Buffer Enable: Enables */
#define PCR_PE_pe1 0x01u   /*!<@brief Pull Enable: Enables */
#define PCR_PS_ps1 0x01u   /*!<@brief Pull Select: Enables internal pullup resistor */

/*! @name PORT1_8 (coord A1), P1_8/J9[32]
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_DEBUG_UART_RX_PORT PORT1               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_DEBUG_UART_RX_PIN 8U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_DEBUG_UART_RX_PIN_MASK (1U << 8U)      /*!<@brief PORT pin mask */
                                                              /* @} */

/*! @name PORT1_9 (coord B1), P1_9/J9[30]
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_DEBUG_UART_TX_PORT PORT1               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_DEBUG_UART_TX_PIN 9U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_DEBUG_UART_TX_PIN_MASK (1U << 9U)      /*!<@brief PORT pin mask */
                                                              /* @} */

/*! @name PORT0_8 (coord C12), RD/FLEXIO_D0
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LIN1_SLP_GPIO GPIO0               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_LIN1_SLP_INIT_GPIO_VALUE 1U       /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_LIN1_SLP_GPIO_PIN 8U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_LIN1_SLP_GPIO_PIN_MASK (1U << 8U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_LIN1_SLP_PORT PORT0               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LIN1_SLP_PIN 8U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LIN1_SLP_PIN_MASK (1U << 8U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORT0_9 (coord A12), WR/FLEXIO0_D1
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LIN1_M_GPIO GPIO0               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_LIN1_M_INIT_GPIO_VALUE 1U       /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_LIN1_M_GPIO_PIN 9U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_LIN1_M_GPIO_PIN_MASK (1U << 9U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_LIN1_M_PORT PORT0               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LIN1_M_PIN 9U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LIN1_M_PIN_MASK (1U << 9U)      /*!<@brief PORT pin mask */
                                                       /* @} */

/*! @name PORT4_5 (coord M8), P4_5/SJ11[3]/J8[6]
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LIN0_M_GPIO GPIO4               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_LIN0_M_INIT_GPIO_VALUE 1U       /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_LIN0_M_GPIO_PIN 5U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_LIN0_M_GPIO_PIN_MASK (1U << 5U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_LIN0_M_PORT PORT4               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LIN0_M_PIN 5U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LIN0_M_PIN_MASK (1U << 5U)      /*!<@brief PORT pin mask */
                                                       /* @} */

/*! @name PORT4_6 (coord N7), P4_6/J8[5]
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LIN0_SLP_GPIO GPIO4               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_LIN0_SLP_INIT_GPIO_VALUE 1U       /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_LIN0_SLP_GPIO_PIN 6U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_LIN0_SLP_GPIO_PIN_MASK (1U << 6U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_LIN0_SLP_PORT PORT4               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LIN0_SLP_PIN 6U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LIN0_SLP_PIN_MASK (1U << 6U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#define PCR_IBE_ibe1 0x01u /*!<@brief Input Buffer Enable: Enables */

/*! @name PORT3_19 (coord K17), P3_19/J5[1]/J1[13]
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITLCDPINS_LCD_BL_GPIO GPIO3                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITLCDPINS_LCD_BL_INIT_GPIO_VALUE 0U        /*!<@brief GPIO output initial state */
#define BOARD_INITLCDPINS_LCD_BL_GPIO_PIN 19U              /*!<@brief GPIO pin number */
#define BOARD_INITLCDPINS_LCD_BL_GPIO_PIN_MASK (1U << 19U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITLCDPINS_LCD_BL_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITLCDPINS_LCD_BL_PIN 19U                   /*!<@brief PORT pin number */
#define BOARD_INITLCDPINS_LCD_BL_PIN_MASK (1U << 19U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*! @name PORT1_3 (coord B4), P1_3/J6[2]
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITLCDPINS_LCD_RST_GPIO GPIO1               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITLCDPINS_LCD_RST_INIT_GPIO_VALUE 1U       /*!<@brief GPIO output initial state */
#define BOARD_INITLCDPINS_LCD_RST_GPIO_PIN 3U              /*!<@brief GPIO pin number */
#define BOARD_INITLCDPINS_LCD_RST_GPIO_PIN_MASK (1U << 3U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITLCDPINS_LCD_RST_PORT PORT1               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITLCDPINS_LCD_RST_PIN 3U                   /*!<@brief PORT pin number */
#define BOARD_INITLCDPINS_LCD_RST_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*! @name PORT3_22 (coord M16), P3_22/J6[5]
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITLCDPINS_LCD_DS_GPIO GPIO3                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITLCDPINS_LCD_DS_INIT_GPIO_VALUE 0U        /*!<@brief GPIO output initial state */
#define BOARD_INITLCDPINS_LCD_DS_GPIO_PIN 22U              /*!<@brief GPIO pin number */
#define BOARD_INITLCDPINS_LCD_DS_GPIO_PIN_MASK (1U << 22U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITLCDPINS_LCD_DS_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITLCDPINS_LCD_DS_PIN 22U                   /*!<@brief PORT pin number */
#define BOARD_INITLCDPINS_LCD_DS_PIN_MASK (1U << 22U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitLcdPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
